---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

user_public_gpg_key_path: "%{cwd}/config/secrets/user/gpg.public"
user_private_gpg_key_path: "%{cwd}/config/secrets/user/gpg.private"
