---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"

  user_public_gpg_key_path: "%{hiera('user_public_gpg_key_path')}"
